---
title: "Homework 2"
output: html_document
date: '2022-04-07'
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(tidyverse)
library(tidymodels)
library(corrplot)
library(ggthemes)
tidymodels_prefer()
```


## Question 1 
```{r}
# read the dataset into a data frame
abalone <- read.csv("~/Downloads/homework-2/data/abalone.csv", header = TRUE)

#add age variable
abalone$age <- abalone$rings + 1.5

abalone %>% 
  ggplot(aes(x = age)) +
  geom_histogram(bins = 60) +
  theme_bw()
```

The distribution of age is skewed to the right.


## Question 2
```{r}
set.seed(2424)

abalone_split <- initial_split(abalone, prop = 0.80,
                                strata = age)
abalone_train <- training(abalone_split) # split abalone data into training & testing set
abalone_test <- testing(abalone_split)
```

## Question 3 
```{r}
# create a recipe predicting the outcome variable, age, with all other predictor variables except rings

abalone_recipe <- 
  recipe(age ~ ., data = abalone_train%>%select(-rings)) %>% 
  step_dummy(all_nominal_predictors()) %>%
  step_interact(terms = ~ starts_with("type"):shucked_weight +longest_shell:diameter + shucked_weight:shell_weight) %>%
  step_center(all_predictors()) %>%
  step_scale(all_predictors())
```
Rings should not be included to predict age because we've already denoted that age = rings + 1.5.

## Question 4
```{r}
# create and store a linear regression object using the "lm" engine.
lm_model <- linear_reg() %>% 
  set_engine("lm")
```


## Question 5
```{r}
# set up an empty workflow, add the model you created in Question 4, and add the recipe that you created in Question 3.
lm_wflow <- workflow() %>% 
  add_model(lm_model) %>% 
  add_recipe(abalone_recipe)
```


## Question 6 
```{r}
longest_shell <- c(0.50)
diameter <- c(0.10)
height <- c(0.30)
whole_weight <- c(4)
shucked_weight <- c(1) 
viscera_weight <- c(2) 
shell_weight <- c(1)
type <- c("F")

df = data.frame(longest_shell, diameter, height, whole_weight, shucked_weight, viscera_weight, shell_weight, type, stringsAsFactors = TRUE)

# Use fit() object to predict the age of a hypothetical female abalone with longest_shell = 0.50, diameter = 0.10, height = 0.30, whole_weight = 4, shucked_weight = 1, viscera_weight = 2, shell_weight = 1.

lm_fit <- fit(lm_wflow, abalone_train%>%select(-rings))

pred <- predict(lm_fit, new_data = df)
pred
```


## Question 7
```{r}
# Use predict() and bind_cols() to create a tibble of model’s predicted values from the training data along with the actual observed ages

abalone_train_res <- predict(lm_fit, new_data = abalone_train %>% select(-age))
abalone_train_res %>% 
  head()

abalone_train_res <- bind_cols(abalone_train_res, abalone_train %>% select(age))
abalone_train_res %>% 
  head()

# Create a metric set that includes R2, RMSE (root mean squared error), and MAE (mean absolute error).
abalone_metrics <- metric_set(rmse, rsq, mae)
abalone_metrics(abalone_train_res, truth = age, 
                estimate = .pred)
```
The R-squared value I got was 0.5674645. This reveals that around 56.75% of the data fit the regression model. The higher an R-squared value is, the better fit the model.
